M48
; DRILL file KiCad 10.0.4-10.0.4~ubuntu22.04.1 date 2026-08-26T15:29:55
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-26T15:29:55+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4-10.0.4~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X185.08Y-101.685
X185.08Y-106.535
T2
X188.11Y-101.385
X188.11Y-106.835
M30
